hdl_global_localization:
  ros__parameters:
    global_localization_engine: BBS
    globalmap_downsample_resolution: 0.1
    query_downsample_resolution: 0.1
    bbs/max_range: 10.0
    bbs/min_tx: -8.0
    bbs/max_tx: 8.0
    bbs/min_ty: -8.0
    bbs/max_ty: 8.0
    bbs/min_theta: -3.15
    bbs/max_theta: 3.15
    bbs/map_min_z: 0.1
    bbs/map_max_z: 1.8
    bbs/map_width: 512
    bbs/map_height: 1024
    bbs/map_resolution: 0.3
    bbs/max_points_per_cell: 5
    bbs/map_pyramid_level: 6
    bbs/scan_min_z: 0.1
    bbs/scan_max_z: 1.2
    fpfh/normal_estimation_radius: 0.3
    fpfh/search_radius: 0.8
    ransac/voxel_based: true
    ransac/max_iterations: 30000
    ransac/matching_budget: 2000
    ransac/max_correspondence_distance: 1.0
    ransac/similarity_threshold: 0.5
    ransac/correspondence_randomness: 2
    ransac/inlier_fraction: 0.25
    ransac/x_min: -10000.0
    ransac/x_max: 10000.0
    ransac/y_min: -10000.0
    ransac/y_max: 10000.0
    ransac/z_min: -10000.0
    ransac/z_max: 10000.0
    ransac/roll_min: -3.15
    ransac/roll_max: 3.15
    ransac/pitch_min: -3.15
    ransac/pitch_max: 3.15
    ransac/yaw_min: -3.15
    ransac/yaw_max: 3.15
